spring:
  cloud:
    gateway:
      routes:
      - id: greeting
        uri: lb://greeting
        predicates:
        - Path=/greeting/**
      - id: name
        uri: lb://name
        predicates:
        - Path=/name/**
