spring:
  cloud:
    gateway:
      routes:
      - id: name
        uri: lb://name
        predicates:
        - Path=/name/{segment}
        filters:
        - SetPath=/{segment}
      - id: greeting
        uri: lb://greeting
        predicates:
        - Path=/greeting/**
